name: My Test
on:
  push:
    branches:
      - i18next

jobs:
  testenv:
    runs-on: macos-latest
    env:
      SETNAME: ${{ secrets.NAME}}
      SETNAMEV: ${{ vars.NAME2 }}
    steps:
      - name: Test env vars
        uses: actions/checkout@v3
      - run: |
          echo "$SETNAME"
          echo "$SETNAMEV"
