# name: cd

# on:
#   push:
#     branches: [main]
#   workflow_dispatch:

# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Write echo
#         run: |
#           echo "this is echo working yah boi" ${{ inputs.release }}
