name: CI
on:
  pull_request:
    branches:
      - prod-othello
    paths-ignore:
      - ".env.sample"
      - "README.md"
  push:
    branches:
      - main
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: v19.9.0
          cache: "npm"
          cache-dependency-path: "./othello/package-lock.json"
      - name: install packages
        run: cd ./othello && npm install

      - name: Run lint
        run: cd ./othello && npm run lint

      - name: Run Test
        run: cd ./othello && npm run test:noWatch
