name: Release!
on:
  workflow_dispatch:
    inputs:
      semver:
        description: The semver to use
        required: true
        default: patch
        type: choice
        options:
          - prerelease
          - prepatch
          - premajor
          - preminor
      release:
        type: boolean
        default: false
      baseTag:
        description: 'base release tag'
      tag:
        description: 'The npm tag'
        required: false
        default: 'latest'
      commit-message:
        description: 'The commit message template'
        required: false
        default: 'Release v1.0.0'
  pull_request:
    types: [closed]
  push:

jobs:
  run-file:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: nearform-actions/optic-release-automation-action@v4
        with:
          commit-message: 'feat(lang): checking this works'
          semver: auto
