name: My Test
on:
  push:
    branches:
      - i18next

jobs:
  testenv:
    runs-on: macos-latest
    env:
      SETNAME: ${{ secrets.NAME}}
      SETNAMEV: ${{ vars.NAME2 }}
    steps:
      - name: Test env vars
        uses: actions/checkout@v3
      - run: |
          echo "$SETNAME"
          echo "$SETNAMEV"
          echo "${{ secrets.NAME}}"
          echo "${{ vars.NAME2 }}"
          echo "${SETNAME}"

      - name: Adding vars to zsh
        run: |
          echo touch ~/.zshrc
          echo "export FILE=${{ secrets.NAME }}" >> ~/.zshrc
          echo "export FILE2=${{ vars.NAME2 }}" >> ~/.zshrc
          echo "export FILE3=${{ env.SETNAMEV }}" >> ~/.zshrc
          echo "export FILE4=$SETNAMEV" >> ~/.zshrc
          echo "export FILE=${{ secrets.NAME }}" >> ~/.bash_profile
          echo "export FILE2=${{ vars.NAME2 }}" >> ~/.bash_profile
          echo "export FILE3=${{ env.SETNAMEV }}" >> ~/.bash_profile
          echo "export FILE4=$SETNAMEV" >> ~/.bash_profile
          echo "export FILE5=testing this ourselves" >> ~/.bash_profile
          source ~/.zshrc

      - name: printing zsh file
        run: |
          cat ~/.zshrc
          source ~/.zshrc
          echo "echoing files out now"
          cat ~/.bash_profile

      - name: echoing the files out
        run: |
          echo " we are echoing - $FILE"
          echo "we are echoing -  $FILE2"
          echo " we are echoing - $FILE3"
          echo "we are echoing -  ${FILE4}"
          echo "we are echoing -  ${FILE5}"
          echo printenv
