name: My Test
on:
  push:
    branches:
      - i18next

jobs:
  testenv:
    runs-on: macos-latest
    env:
      SETNAME: ${{ secrets.NAME}}
      SETNAMEV: ${{ vars.NAME2 }}
    steps:
      - name: Test env vars
        uses: actions/checkout@v3
      - run: |
          echo "$SETNAME"
          echo "$SETNAMEV"
          echo "${{ secrets.NAME}}"
          echo "${{ vars.NAME2 }}"

      - name: Adding vars to zsh
        run: |
          echo "export FILE=${{ secrets.NAME }}" >> ~/.zshrc
          echo "export FILE2=${{ vars.NAME2 }}" >> ~/.zshrc
          source ~/.zshrc

      - name: printing envs in zsh
        run: |
          cat ~/.zshrc
          echo "echoing files out now"
          echo "$FILE"
          echo "$FILE2"
          echo printenv
